# Schema for the configuration files of the message module.

message.settings:
  type: config_object
  label: 'Field settings'
  mapping:
    delete_cron_limit:
      type: integer
      label: 'Number of entities we should iterate each cron task'
    delete_on_entity_delete:
      type: sequence
      sequence:
        - type: string
    purge_enable:
      type: boolean
    purge_methods:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          enabled:
            type: boolean
          data:
            type: message.purge.[%parent.id]
          weight:
            type: integer

message.template.*:
  type: config_entity
  label: 'Message template'
  mapping:
    template:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    text:
      type: sequence
      label: 'Message Text'
      sequence:
        - type: text
          label: 'Text'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        'token options':
          type: mapping
          label: 'Token options'
          mapping:
            clear:
              type: boolean
              label: 'Clear empty tokens'
            token replace:
              type: boolean
              label: 'Replace tokens'
        purge_override:
          type: boolean
          label: 'Override global purge settings'
        purge_methods:
          type: sequence
          label: 'Purge methods'
          sequence:
            type: mapping
            mapping:
              id:
                type: string
              enabled:
                type: boolean
              data:
                type: message.purge.[%parent.id]
              weight:
                type: integer

action.configuration.message_delete_action:
  type: action_configuration_default
  label: 'Delete message configuration'

message.message:
  type: mapping
  label: 'Message settings'
  mapping:
    purge_enable:
      type: boolean
      label: 'Purge messages'
    delete_on_entity_delete:
      type: sequence
      label: 'Auto delete messages referencing the following entities'
      sequence:
        - type: string
          label: 'Entity type'
    delete_cron_limit:
      type: integer
      label: 'The maximal amount of messages to purge per cron run.'


# This is modeled the same as image styles are - each plugin has its own config.
# @see image.schema.yml
message.purge.*:
  type: mapping
  label: 'Purge settings'


message.purge.days:
  type: mapping
  label: 'Days'
  mapping:
    days:
      label: 'Purge messages older than'
      type: integer


message.purge.quota:
  type: mapping
  label: 'Quota'
  mapping:
    quota:
      label: 'Messages quota'
      type: integer
